ssh_authorized_keys:
- github:metabsd
write_files:
- path: /var/lib/connman/default.config
  content: |-
    [service_eth0]
    Type=ethernet
    IPv4=192.168.2.11/255.255.255.0/192.168.2.1
    IPv6=off
    Nameservers=192.168.2.1
- encoding: ""
  content: |-
    #!/bin/bash
    echo hello, local service start
  owner: root
  path: /etc/local.d/example.start
  permissions: '0755'
hostname: k3os-01
init_cmd:
- "echo hello, init command"
boot_cmd:
- "echo hello, boot command"
run_cmd:
- "echo hello, run command"
k3os:
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: $1$eVSINn4S$s9QauHFfk9wcgfzTWI3du1
  labels:
    somekey: somevalue
  k3s_args:
  - server
  - "--disable-agent"
