ssh_authorized_keys:
- github:metabsd
write_files:
- path: /var/lib/connman/default.config
  content: |-
    [service_eth0]
    Type=ethernet
    IPv4=192.168.2.13/255.255.255.0/192.168.2.1
    IPv6=off
    Nameservers=192.168.2.1
hostname: k3os-node-02
k3os:
  data_sources:
  - cdrom
  dns_nameservers:
  - 192.168.2.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: $1$eVSINn4S$s9QauHFfk9wcgfzTWI3du1
  server_url: https://192.168.2.11:6443
  token: iT6gmQwLV4CYNZz3GfJy
