---

- name: stop and disable firewalld
  service:
     name: firewalld
     state: stopped
     enabled: no

- name: install haproxy
  package:
     name:
        - haproxy
     state: latest

- name: install haproxy config
  template:
     src: haproxy.cfg.j2
     dest: /etc/haproxy/haproxy.cfg
  register: config_changed

- name: restart and enable haproxy
  service:
     name: haproxy
     state: restarted
     enabled: yes
  when: config_changed.changed